// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4XsV8Oh9PPCHxxw5VCp4umrE-GOUhKEQ',
    appId: '1:397013667016:web:819fac3136f0c29cc869fd',
    messagingSenderId: '397013667016',
    projectId: 'arctive-92040',
    authDomain: 'arctive-92040.firebaseapp.com',
    storageBucket: 'arctive-92040.firebasestorage.app',
    measurementId: 'G-9P37H2LKLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlNj3vx442QYu3PxwXM9CsRPcX7DGuHWE',
    appId: '1:397013667016:android:c47e8039089cfbe6c869fd',
    messagingSenderId: '397013667016',
    projectId: 'arctive-92040',
    storageBucket: 'arctive-92040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLAUATH5sd59mBywkDoFAqqOnnXjf1NjI',
    appId: '1:397013667016:ios:7059ddec736b5a31c869fd',
    messagingSenderId: '397013667016',
    projectId: 'arctive-92040',
    storageBucket: 'arctive-92040.firebasestorage.app',
    iosBundleId: 'com.example.acrtive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLAUATH5sd59mBywkDoFAqqOnnXjf1NjI',
    appId: '1:397013667016:ios:7059ddec736b5a31c869fd',
    messagingSenderId: '397013667016',
    projectId: 'arctive-92040',
    storageBucket: 'arctive-92040.firebasestorage.app',
    iosBundleId: 'com.example.acrtive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4XsV8Oh9PPCHxxw5VCp4umrE-GOUhKEQ',
    appId: '1:397013667016:web:089b35c733f27801c869fd',
    messagingSenderId: '397013667016',
    projectId: 'arctive-92040',
    authDomain: 'arctive-92040.firebaseapp.com',
    storageBucket: 'arctive-92040.firebasestorage.app',
    measurementId: 'G-0R3CJGT6SZ',
  );
}
